"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

#   Build paths inside the project like this: BASE_DIR / 'subdir'.
#   BASE DIRECTORY  # ✅ FIRST define BASE_DIR
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ==============================
# LOAD ENVIRONMENT VARIABLES    and   # ✅ THEN load .env using BASE_DIR
# ==============================
#load_dotenv()

# Load .env with BASE_DIR (safer)
load_dotenv(BASE_DIR / ".env")      #This ensures Django always reads the correct .env.





# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# ==============================
# SECURITY SETTINGS
# ==============================
SECRET_KEY = os.getenv("SECRET_KEY")

#SECRET_KEY = 'django-insecure-er1l)4_5&+&ia-dvz_y3v0gg1(#($(^m)$v3gi*!2a378m(pqk'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True  # ❗ Change to False in production

#For Prodection point of you
DEBUG = os.getenv("DEBUG") == "True"


#  ALLOWED_HOSTS = []  #['yourdomain.com']

#  ALLOWED_HOSTS should come from env
#ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'scraper',   # 👈 YOUR APP  # existing app
    'events',    # 👈 new app added
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',   #Enable Refresh Token Rotation (Advanced Security)
    'django_filters',
    'drf_yasg',
]

# ==============================
# MIDDLEWARE
# ==============================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ==============================
# ROOT URL
# ==============================

ROOT_URLCONF = 'backend.urls'

# ==============================
# TEMPLATES
# ==============================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================
# REST FRAMEWORK CONFIGURATION
# ==============================

"""
# first we have simply this one before filtration and search
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5
}
"""

REST_FRAMEWORK = {
    #Every API now requires login
    #Token must be sent in header
    #DEFAULT_AUTHENTICATION_CLASSES , DEFAULT_PERMISSION_CLASSES this two function is for authentication
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',  # for admin login/ browsable API/for Basic login
       # 'rest_framework.authentication.BasicAuthentication',    # For Basic Auth
        'rest_framework_simplejwt.authentication.JWTAuthentication',    # for API / for JWT auth 
    ),

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    #----------------------------------------------------------------------------
    #logic of pagination
    #'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_PAGINATION_CLASS': 'events.pagination.CustomPagination',
    'PAGE_SIZE': 5,

    #logic of filteration 
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

#Right now Swagger is still detecting BasicAuthentication from DRF settings.
#We must explicitly configure Swagger to use JWT Bearer.

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,  # ❗ Disable Django login (Basic Auth) or Hide Django login button in Swagger
   
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'Enter: Bearer <your_access_token>'
        }
    }
}

"""
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': True,  # Enable Django login button

    'SECURITY_DEFINITIONS': {
        'Basic': {
            'type': 'basic'
        },
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'Enter: Bearer <your_access_token>'
        }
    }
}
"""

# ==============================
# JWT CONFIGURATION
# ==============================
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15), #Access token → short life (10–15 mins)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),    #Refresh token → longer (7–14 days)
    
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# ==============================
# INTERNATIONALIZATION
# ==============================
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata' # OR  'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATIC_URL = 'static/'                      #Static settings
STATIC_ROOT = BASE_DIR / "staticfiles"      #Without this, collectstatic fails in production.

# ==============================
# REDIS CACHE CONFIGURATION
# ==============================
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

#Add Media settings
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

#Default auto field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Add LOGGING block

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "django.log",
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
}