# Generated by Django 6.0 on 2026-02-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='Social media platform name (Twitter, Instagram, etc.)', max_length=50)),
                ('username', models.CharField(help_text='Username of the account', max_length=150)),
                ('post_text', models.TextField(help_text='Content of the post')),
                ('post_url', models.URLField(help_text='Direct URL of the post', max_length=500, unique=True)),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='Number of likes')),
                ('comments_count', models.PositiveIntegerField(default=0, help_text='Number of comments')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, help_text='Time when the post was scraped')),
            ],
        ),
    ]
